### PR TITLE
https://github.com/leocavalcante/page_view_indicator/issues/17

### LINKED ISSUE #17: Page indicator length not updated if dynamically changed
Hi, basically same issue as this one - https://github.com/leocavalcante/page_view_indicator/issues/1
If PageViewIndicator is inside StreamBuilder and item count is dynamically changed, the number of indicators stays the same. Here is a quick code to reproduce the issue:
```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:page_view_indicator/page_view_indicator.dart';

class App extends StatefulWidget {
  @override
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  final pageIndexNotifier = ValueNotifier<int>(0);
  int _counter = 2;
  StreamController<int> _events;

  @override
  void initState() {
    super.initState();
    _events = StreamController<int>();
    _events.add(_counter);
  }

  void _incrementCounter() {
    _counter++;
    _events.add(_counter);
  }

  void _decrementCounter() {
    if (_counter > 1) {
      _counter--;
      _events.add(_counter);
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: StreamBuilder<int>(
          stream: _events.stream,
          builder: (context, snapshot) {
            if (!snapshot.hasData) {
              return const SizedBox.shrink();
            }

            return Stack(
              alignment: FractionalOffset.bottomCenter,
              children: <Widget>[
                PageView.builder(
                  onPageChanged: (index) => pageIndexNotifier.value = index,
                  itemCount: snapshot.data,
                  itemBuilder: (context, index) {
                    return Container(
                      decoration: BoxDecoration(color: Colors.accents[index]),
                    );
                  },
                ),
                _buildExample1(snapshot.data),
                Center(
                  child: Text(snapshot.data.toString()),
                ),
              ],
            );
          },
        ),
        floatingActionButton: Column(
          crossAxisAlignment: CrossAxisAlignment.end,
          mainAxisAlignment: MainAxisAlignment.end,
          children: <Widget>[
            FloatingActionButton(
              onPressed: _incrementCounter,
              tooltip: 'Increment',
              child: Icon(Icons.exposure_plus_1),
            ),
            const SizedBox(height: 16),
            FloatingActionButton(
              onPressed: _decrementCounter,
              tooltip: 'Decrement',
              child: Icon(Icons.exposure_neg_1),
            ),
          ],
        ),
      ),
    );
  }

  PageViewIndicator _buildExample1(int length) {
    return PageViewIndicator(
      pageIndexNotifier: pageIndexNotifier,
      length: length,
      normalBuilder: (animationController, index) => Circle(
        size: 8.0,
        color: Colors.black87,
      ),
      highlightedBuilder: (animationController, index) => ScaleTransition(
        scale: CurvedAnimation(
          parent: animationController,
          curve: Curves.ease,
        ),
        child: Circle(
          size: 12.0,
          color: Colors.accents.elementAt(9),
        ),
      ),
    );
  }
}

void main() => runApp(App());
```

### PR DESCRIPTION
**Pull request by liri2006**
Page indicator length not updated if dynamically changed
Closes #17

### CODE REVIEW

**Comment by leocavalcante** [comment]
Great, thank you!

**Comment by liri2006** [comment]
@leocavalcante Thanx! Can you publish new package when you have a minute?

**Comment by leocavalcante** [comment]
@liri2006 its on 2.0.4: https://pub.dev/packages/page_view_indicator/versions/2.0.4

**Comment by liri2006** [comment]
@leocavalcante Thank you!

**Pull request merged**
